[I 15:00:34.670 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 15:00:34.671 NotebookApp] Serving notebooks from local directory: /Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024
[I 15:00:34.671 NotebookApp] The Jupyter Notebook is running at:
[I 15:00:34.671 NotebookApp] http://localhost:8888/?token=978e6f0ad6898829e918dc2e1952938c09a2983ed8333668
[I 15:00:34.671 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:00:34.678 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/wenbin/Library/Jupyter/runtime/nbserver-6217-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=978e6f0ad6898829e918dc2e1952938c09a2983ed8333668
[I 15:00:48.949 NotebookApp] Creating new notebook in 
[I 15:00:50.033 NotebookApp] Kernel started: 82a74e87-3bf8-49f5-b018-42b902517722
[W 15:00:50.055 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190425150034 (::1) 15.31ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=python3
[I 15:00:50.717 NotebookApp] Adapting to protocol v5.1 for kernel 82a74e87-3bf8-49f5-b018-42b902517722
[W 15:01:02.503 NotebookApp] 404 GET /api/contents/GruntNote.ipynb?type=notebook&content=0&_=1556168449732 (::1): No such file or directory: GruntNote.ipynb
[W 15:01:02.503 NotebookApp] No such file or directory: GruntNote.ipynb
[W 15:01:02.504 NotebookApp] 404 GET /api/contents/GruntNote.ipynb?type=notebook&content=0&_=1556168449732 (::1) 1.76ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=python3
[I 15:01:02.510 NotebookApp] Uploading file to /GruntNote.ipynb
[I 15:09:33.421 NotebookApp] Saving file at /GruntNote.ipynb
[I 15:09:33.442 NotebookApp] Saving file at /GruntNote.ipynb
[I 15:09:33.457 NotebookApp] Saving file at /GruntNote.ipynb
[I 15:09:33.470 NotebookApp] Saving file at /GruntNote.ipynb
[I 15:12:24.081 NotebookApp] Kernel started: dff2ea20-5352-46ad-8f31-4d76f856d3e8
[W 15:12:24.115 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190425150034 (::1) 2.60ms referer=http://localhost:8888/notebooks/CouchdbNote.ipynb
[I 15:12:24.836 NotebookApp] Adapting to protocol v5.1 for kernel dff2ea20-5352-46ad-8f31-4d76f856d3e8
[I 16:16:34.531 NotebookApp] Saving file at /GruntNote.ipynb
[I 16:18:07.992 NotebookApp] Saving file at /GruntNote.ipynb
[I 16:18:09.457 NotebookApp] Saving file at /GruntNote.ipynb
[I 16:19:20.082 NotebookApp] Starting buffering for dff2ea20-5352-46ad-8f31-4d76f856d3e8:6132d7b563a64eb38f3075d3a593e9e6
[I 16:19:20.652 NotebookApp] Starting buffering for 82a74e87-3bf8-49f5-b018-42b902517722:f18ff87733724d818276409811ec734a
[C 20:43:54.343 NotebookApp] received signal 15, stopping
[I 20:43:54.346 NotebookApp] Shutting down 2 kernels
[I 20:43:54.548 NotebookApp] Kernel shutdown: 82a74e87-3bf8-49f5-b018-42b902517722
[I 20:43:54.550 NotebookApp] Kernel shutdown: dff2ea20-5352-46ad-8f31-4d76f856d3e8
[I 11:09:02.594 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 11:09:02.595 NotebookApp] Serving notebooks from local directory: /Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024
[I 11:09:02.595 NotebookApp] The Jupyter Notebook is running at:
[I 11:09:02.595 NotebookApp] http://localhost:8888/?token=b23154d5e8be2941e0a394b879bdd705a16b6a81e0eaf00e
[I 11:09:02.595 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:09:02.601 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/wenbin/Library/Jupyter/runtime/nbserver-1520-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=b23154d5e8be2941e0a394b879bdd705a16b6a81e0eaf00e
[I 11:09:37.866 NotebookApp] Kernel started: 17d6afe4-ceea-48ec-a5b6-13e2fbb04dc4
[W 11:09:37.881 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190426110901 (::1) 11.62ms referer=http://localhost:8888/notebooks/GruntNote.ipynb
[I 11:09:38.650 NotebookApp] Adapting to protocol v5.1 for kernel 17d6afe4-ceea-48ec-a5b6-13e2fbb04dc4
[I 11:09:41.627 NotebookApp] Starting buffering for 17d6afe4-ceea-48ec-a5b6-13e2fbb04dc4:c12ee14700b9429299af383fd405675e
[I 11:09:47.752 NotebookApp] Kernel started: 15d92591-41be-42d4-8428-15464ea0623a
[W 11:09:47.773 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190426110901 (::1) 4.24ms referer=http://localhost:8888/notebooks/Untitled.ipynb
[I 11:09:48.435 NotebookApp] Adapting to protocol v5.1 for kernel 15d92591-41be-42d4-8428-15464ea0623a
[I 11:09:49.426 NotebookApp] Starting buffering for 15d92591-41be-42d4-8428-15464ea0623a:850df70d74214b62982c949c716c1ff8
[W 11:09:56.018 NotebookApp] delete /Untitled.ipynb
[I 11:10:07.083 NotebookApp] Kernel shutdown: 17d6afe4-ceea-48ec-a5b6-13e2fbb04dc4
[I 11:10:07.925 NotebookApp] Kernel shutdown: 15d92591-41be-42d4-8428-15464ea0623a
[I 11:10:16.085 NotebookApp] Kernel started: d7b508e3-460d-4026-8990-6191a036e653
[W 11:10:16.132 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190426110901 (::1) 4.41ms referer=http://localhost:8888/notebooks/CouchdbNote.ipynb
[I 11:10:16.810 NotebookApp] Adapting to protocol v5.1 for kernel d7b508e3-460d-4026-8990-6191a036e653
[I 11:23:27.623 NotebookApp] Starting buffering for d7b508e3-460d-4026-8990-6191a036e653:829b107aa26c4efe9bc6396e049971a1
[I 11:28:58.270 NotebookApp] 302 GET / (::1) 0.61ms
[I 11:29:01.585 NotebookApp] Adapting to protocol v5.1 for kernel d7b508e3-460d-4026-8990-6191a036e653
[W 11:29:01.599 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190426110901 (::1) 1.98ms referer=http://localhost:8888/notebooks/CouchdbNote.ipynb
[I 11:31:02.320 NotebookApp] Saving file at /CouchdbNote.ipynb
[I 13:13:13.284 NotebookApp] Starting buffering for d7b508e3-460d-4026-8990-6191a036e653:fcfd947ce9df4f1d84b9d746fb35304b
[I 14:10:08.073 NotebookApp] 302 GET / (::1) 0.49ms
[W 14:10:10.848 NotebookApp] Notebook CouchdbNote.ipynb is not trusted
[I 14:10:11.431 NotebookApp] Adapting to protocol v5.1 for kernel d7b508e3-460d-4026-8990-6191a036e653
[W 14:10:11.447 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190426110901 (::1) 2.91ms referer=http://localhost:8888/notebooks/CouchdbNote.ipynb
[I 14:12:11.949 NotebookApp] Saving file at /CouchdbNote.ipynb
[I 14:16:11.946 NotebookApp] Saving file at /CouchdbNote.ipynb
[I 16:04:12.251 NotebookApp] Saving file at /CouchdbNote.ipynb
[I 16:04:17.334 NotebookApp] Starting buffering for d7b508e3-460d-4026-8990-6191a036e653:309bdd7bb4534e7abe53e666b415b0b7
[W 16:04:22.228 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190426110901 (::1) 1.80ms referer=http://localhost:8888/notebooks/CouchdbNote.ipynb
[I 16:04:22.934 NotebookApp] Adapting to protocol v5.1 for kernel d7b508e3-460d-4026-8990-6191a036e653
[I 16:04:41.916 NotebookApp] Saving file at /CouchdbNote.ipynb
[I 16:04:42.775 NotebookApp] Starting buffering for d7b508e3-460d-4026-8990-6191a036e653:61aec1dcc303477bb291e462758716e5
[I 10:12:31.189 NotebookApp] The port 8888 is already in use, trying another port.
[I 10:12:31.191 NotebookApp] The port 8889 is already in use, trying another port.
[I 10:12:31.233 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 10:12:31.233 NotebookApp] Serving notebooks from local directory: /Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024
[I 10:12:31.233 NotebookApp] The Jupyter Notebook is running at:
[I 10:12:31.233 NotebookApp] http://localhost:8890/?token=2f4184e02ced3a7d598c9ff9b27509048ce549f5f701357d
[I 10:12:31.233 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:12:31.239 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/wenbin/Library/Jupyter/runtime/nbserver-6830-open.html
    Or copy and paste one of these URLs:
        http://localhost:8890/?token=2f4184e02ced3a7d598c9ff9b27509048ce549f5f701357d
[W 10:12:37.222 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190427101230 (::1) 9.57ms referer=http://localhost:8890/notebooks/GruntNote.ipynb
[I 10:12:37.567 NotebookApp] Kernel started: ce19d680-420b-4c12-acee-49a44e2abb16
[I 10:12:38.344 NotebookApp] Adapting to protocol v5.1 for kernel ce19d680-420b-4c12-acee-49a44e2abb16
[I 10:14:37.544 NotebookApp] Saving file at /GruntNote.ipynb
[W 10:15:50.497 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190427101230 (::1) 2.33ms referer=http://localhost:8890/notebooks/CouchdbNote.ipynb
[I 10:15:51.136 NotebookApp] Kernel started: 78d9a7d4-e13b-4167-b69d-ce1a07b0a03c
[I 10:15:51.903 NotebookApp] Adapting to protocol v5.1 for kernel 78d9a7d4-e13b-4167-b69d-ce1a07b0a03c
[I 10:16:37.352 NotebookApp] Saving file at /CouchdbNote.ipynb
[I 10:16:37.397 NotebookApp] Starting buffering for 78d9a7d4-e13b-4167-b69d-ce1a07b0a03c:285f2c9dafe7439988147f0eb77f9714
[I 10:16:37.995 NotebookApp] Starting buffering for ce19d680-420b-4c12-acee-49a44e2abb16:2d278d7f573642d59e0c81c30fbd472f
[I 10:18:25.225 NotebookApp] Creating new file in 
[I 10:19:19.061 NotebookApp] Creating new notebook in 
[I 10:19:19.844 NotebookApp] Kernel started: 11157e67-db00-43b7-a3e3-048727383d79
[W 10:19:19.854 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190427101230 (::1) 6.92ms referer=http://localhost:8890/notebooks/Untitled.ipynb?kernel_name=python3
[I 10:19:20.525 NotebookApp] Adapting to protocol v5.1 for kernel 11157e67-db00-43b7-a3e3-048727383d79
[I 10:21:20.531 NotebookApp] Saving file at /Untitled.ipynb
[W 10:21:24.575 NotebookApp] delete /untitled.txt
[I 10:28:28.996 NotebookApp] Adapting to protocol v5.1 for kernel ce19d680-420b-4c12-acee-49a44e2abb16
[W 10:28:29.009 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190427101230 (::1) 5.11ms referer=http://localhost:8890/notebooks/GruntNote.ipynb
[I 11:01:20.290 NotebookApp] Saving file at /Untitled.ipynb
[I 11:03:21.294 NotebookApp] Saving file at /Untitled.ipynb
[W 11:20:42.545 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190427101230 (::1) 2.09ms referer=http://localhost:8890/notebooks/CouchdbNote.ipynb
[I 11:20:43.230 NotebookApp] Adapting to protocol v5.1 for kernel 78d9a7d4-e13b-4167-b69d-ce1a07b0a03c
[I 11:20:51.641 NotebookApp] Starting buffering for 78d9a7d4-e13b-4167-b69d-ce1a07b0a03c:2675d740deef47178138c6b32a81c235
[I 11:31:20.748 NotebookApp] Saving file at /Untitled.ipynb
[I 11:37:19.869 NotebookApp] Saving file at /Untitled.ipynb
[I 11:39:20.542 NotebookApp] Saving file at /Untitled.ipynb
[I 11:40:29.551 NotebookApp] Saving file at /GruntNote.ipynb
[I 11:41:19.857 NotebookApp] Saving file at /Untitled.ipynb
[I 11:43:19.856 NotebookApp] Saving file at /Untitled.ipynb
[I 11:45:19.857 NotebookApp] Saving file at /Untitled.ipynb
[I 11:47:20.556 NotebookApp] Saving file at /Untitled.ipynb
[I 11:48:29.552 NotebookApp] Saving file at /GruntNote.ipynb
[I 11:49:19.861 NotebookApp] Saving file at /Untitled.ipynb
[I 11:51:19.857 NotebookApp] Saving file at /Untitled.ipynb
[I 11:52:29.554 NotebookApp] Saving file at /GruntNote.ipynb
[I 11:53:11.226 NotebookApp] Saving file at /Untitled.ipynb
[I 11:55:19.863 NotebookApp] Saving file at /Untitled.ipynb
[I 11:57:19.863 NotebookApp] Saving file at /Untitled.ipynb
[I 11:59:19.862 NotebookApp] Saving file at /Untitled.ipynb
[I 13:25:57.887 NotebookApp] Saving file at /Untitled.ipynb
[I 13:27:57.712 NotebookApp] Saving file at /Untitled.ipynb
[I 13:29:58.392 NotebookApp] Saving file at /Untitled.ipynb
[I 13:31:57.710 NotebookApp] Saving file at /Untitled.ipynb
[I 13:33:58.394 NotebookApp] Saving file at /Untitled.ipynb
[I 13:35:58.395 NotebookApp] Saving file at /Untitled.ipynb
[I 13:39:58.407 NotebookApp] Saving file at /Untitled.ipynb
[I 13:43:57.714 NotebookApp] Saving file at /Untitled.ipynb
[I 13:45:57.712 NotebookApp] Saving file at /Untitled.ipynb
[I 13:47:57.715 NotebookApp] Saving file at /Untitled.ipynb
[I 13:49:57.716 NotebookApp] Saving file at /Untitled.ipynb
[I 13:51:57.716 NotebookApp] Saving file at /Untitled.ipynb
[I 14:17:58.745 NotebookApp] Saving file at /Untitled.ipynb
[I 14:21:00.523 NotebookApp] Saving file at /Untitled.ipynb
[I 14:21:03.459 NotebookApp] Saving file at /Untitled.ipynb
[I 14:37:57.721 NotebookApp] Saving file at /Untitled.ipynb
[I 14:39:57.724 NotebookApp] Saving file at /Untitled.ipynb
[I 14:41:57.724 NotebookApp] Saving file at /Untitled.ipynb
[I 14:43:57.721 NotebookApp] Saving file at /Untitled.ipynb
[I 14:45:52.770 NotebookApp] Starting buffering for ce19d680-420b-4c12-acee-49a44e2abb16:7445cbef3e3146d687aac779ce0543bb
[I 14:45:54.604 NotebookApp] Saving file at /Untitled.ipynb
[I 14:45:54.840 NotebookApp] Saving file at /Untitled.ipynb
[I 14:45:55.011 NotebookApp] Saving file at /Untitled.ipynb
[I 14:47:57.726 NotebookApp] Saving file at /Untitled.ipynb
[I 14:49:57.725 NotebookApp] Saving file at /Untitled.ipynb
[I 14:55:57.722 NotebookApp] Saving file at /Untitled.ipynb
[I 14:57:59.184 NotebookApp] Saving file at /Untitled.ipynb
[I 15:03:57.729 NotebookApp] Saving file at /Untitled.ipynb
[I 15:05:57.850 NotebookApp] Saving file at /Untitled.ipynb
[I 15:23:57.730 NotebookApp] Saving file at /Untitled.ipynb
[I 15:25:58.414 NotebookApp] Saving file at /Untitled.ipynb
[I 15:27:57.732 NotebookApp] Saving file at /Untitled.ipynb
[I 15:29:58.032 NotebookApp] Saving file at /Untitled.ipynb
[I 15:31:57.733 NotebookApp] Saving file at /Untitled.ipynb
[I 15:33:58.416 NotebookApp] Saving file at /Untitled.ipynb
[I 15:37:58.449 NotebookApp] Saving file at /Untitled.ipynb
[I 15:39:58.615 NotebookApp] Saving file at /Untitled.ipynb
[I 15:41:58.818 NotebookApp] Saving file at /Untitled.ipynb
[I 16:07:22.657 NotebookApp] Starting buffering for 11157e67-db00-43b7-a3e3-048727383d79:ea4c14d0e6604b49a21426589cf0b870
[C 10:41:58.948 NotebookApp] received signal 15, stopping
[I 10:41:58.960 NotebookApp] Shutting down 3 kernels
[C 10:41:58.956 NotebookApp] received signal 15, stopping
[I 10:41:58.969 NotebookApp] Shutting down 1 kernel
[I 10:41:59.380 NotebookApp] Kernel shutdown: ce19d680-420b-4c12-acee-49a44e2abb16
[I 10:41:59.382 NotebookApp] Kernel shutdown: 78d9a7d4-e13b-4167-b69d-ce1a07b0a03c
[I 10:41:59.383 NotebookApp] Kernel shutdown: 11157e67-db00-43b7-a3e3-048727383d79
[I 10:41:59.388 NotebookApp] Kernel shutdown: d7b508e3-460d-4026-8990-6191a036e653
[I 10:40:12.958 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 10:40:12.959 NotebookApp] Serving notebooks from local directory: /Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024
[I 10:40:12.959 NotebookApp] The Jupyter Notebook is running at:
[I 10:40:12.959 NotebookApp] http://localhost:8888/?token=97e6d73369622263252ca796c438565f0124fa6f0dab7b8e
[I 10:40:12.959 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:40:12.966 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/wenbin/Library/Jupyter/runtime/nbserver-9745-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=97e6d73369622263252ca796c438565f0124fa6f0dab7b8e
[I 10:40:19.083 NotebookApp] Saving file at /Untitled.ipynb
[I 10:40:24.137 NotebookApp] Kernel started: 0f8ad24c-6d26-4fac-af70-d8d1586ed947
[W 10:40:24.486 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190430104012 (::1) 10.61ms referer=http://localhost:8888/notebooks/Untitled.ipynb
[I 10:40:24.888 NotebookApp] Adapting to protocol v5.1 for kernel 0f8ad24c-6d26-4fac-af70-d8d1586ed947
[I 10:42:24.397 NotebookApp] Saving file at /Untitled.ipynb
[I 10:58:24.214 NotebookApp] Saving file at /Untitled.ipynb
[I 11:00:24.780 NotebookApp] Saving file at /Untitled.ipynb
[I 11:10:23.743 NotebookApp] Saving file at /Untitled.ipynb
[I 11:10:24.827 NotebookApp] Saving file at /Untitled.ipynb
[I 11:10:25.788 NotebookApp] Starting buffering for 0f8ad24c-6d26-4fac-af70-d8d1586ed947:2f9ad30e9adc4d7b9689d046d6362179
[I 17:56:21.835 NotebookApp] 302 GET / (::1) 12.44ms
[I 22:47:03.824 NotebookApp] 302 GET / (::1) 3.85ms
[I 23:26:06.648 NotebookApp] 302 GET / (::1) 0.61ms
[I 23:26:10.335 NotebookApp] Adapting to protocol v5.1 for kernel 0f8ad24c-6d26-4fac-af70-d8d1586ed947
[W 23:26:10.550 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190430104012 (::1) 2.28ms referer=http://localhost:8888/notebooks/Untitled.ipynb
[I 23:26:10.830 NotebookApp] Starting buffering for 0f8ad24c-6d26-4fac-af70-d8d1586ed947:697ef6dd91e44b76ada420677733cc71
[I 23:26:14.044 NotebookApp] Kernel started: a60d6a40-12b0-4752-bae6-e575ada195c6
[W 23:26:14.308 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190430104012 (::1) 3.01ms referer=http://localhost:8888/notebooks/CouchdbNote.ipynb
[I 23:26:14.880 NotebookApp] Adapting to protocol v5.1 for kernel a60d6a40-12b0-4752-bae6-e575ada195c6
[I 23:26:52.005 NotebookApp] Saving file at /CouchdbNote.ipynb
[I 23:26:52.966 NotebookApp] Saving file at /CouchdbNote.ipynb
[I 23:26:53.545 NotebookApp] Saving file at /CouchdbNote.ipynb
[I 23:26:53.711 NotebookApp] Saving file at /CouchdbNote.ipynb
[I 23:26:53.930 NotebookApp] Saving file at /CouchdbNote.ipynb
[I 23:27:04.708 NotebookApp] Saving file at /CouchdbNote.ipynb
[I 23:30:40.030 NotebookApp] Adapting to protocol v5.1 for kernel 0f8ad24c-6d26-4fac-af70-d8d1586ed947
[W 23:30:40.216 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190430104012 (::1) 2.13ms referer=http://localhost:8888/notebooks/Untitled.ipynb
[I 23:32:40.212 NotebookApp] Saving file at /Untitled.ipynb
[I 23:42:40.227 NotebookApp] Saving file at /Untitled.ipynb
[I 00:00:38.691 NotebookApp] Starting buffering for 0f8ad24c-6d26-4fac-af70-d8d1586ed947:6b0ccc5984074e259f68d8c31ffcc26c
[I 00:00:39.024 NotebookApp] Starting buffering for a60d6a40-12b0-4752-bae6-e575ada195c6:97b1e1b4e19c4bf0833e9a09ad1dd8df
[C 01:20:21.493 NotebookApp] received signal 15, stopping
[I 01:20:21.500 NotebookApp] Shutting down 2 kernels
[I 01:20:21.809 NotebookApp] Kernel shutdown: 0f8ad24c-6d26-4fac-af70-d8d1586ed947
[I 01:20:21.811 NotebookApp] Kernel shutdown: a60d6a40-12b0-4752-bae6-e575ada195c6
[I 18:03:27.910 NotebookApp] The port 8888 is already in use, trying another port.
[I 18:03:27.935 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 18:03:27.935 NotebookApp] Serving notebooks from local directory: /Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024
[I 18:03:27.935 NotebookApp] The Jupyter Notebook is running at:
[I 18:03:27.936 NotebookApp] http://localhost:8889/?token=ecfd4d30206487f2297dbede6586ad59931903a6fedfd022
[I 18:03:27.936 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:03:27.940 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/wenbin/Library/Jupyter/runtime/nbserver-4708-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=ecfd4d30206487f2297dbede6586ad59931903a6fedfd022
[I 18:03:36.208 NotebookApp] Kernel started: 0b088d07-f9d0-4244-af4c-424b76f9d1f0
[W 18:03:36.501 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190504180327 (::1) 16.48ms referer=http://localhost:8889/notebooks/Preprocess/Preprocess.ipynb
[I 18:03:37.150 NotebookApp] Adapting to protocol v5.1 for kernel 0b088d07-f9d0-4244-af4c-424b76f9d1f0
[I 18:05:36.188 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:07:36.649 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:09:36.185 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:11:36.185 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:13:36.185 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:14:32.845 NotebookApp] Starting buffering for 0b088d07-f9d0-4244-af4c-424b76f9d1f0:fc5c2073fd144d56ab3a86a125dc6137
[I 18:14:33.576 NotebookApp] Kernel restarted: 0b088d07-f9d0-4244-af4c-424b76f9d1f0
[I 18:14:34.187 NotebookApp] Adapting to protocol v5.1 for kernel 0b088d07-f9d0-4244-af4c-424b76f9d1f0
[I 18:14:34.188 NotebookApp] Restoring connection for 0b088d07-f9d0-4244-af4c-424b76f9d1f0:fc5c2073fd144d56ab3a86a125dc6137
[I 18:14:34.188 NotebookApp] Replaying 6 buffered messages
[I 18:15:36.481 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:19:17.987 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:19:21.251 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:19:22.200 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:29:36.186 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:31:36.193 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:33:37.182 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:34:27.941 NotebookApp] Starting buffering for 0b088d07-f9d0-4244-af4c-424b76f9d1f0:fc5c2073fd144d56ab3a86a125dc6137
[I 18:34:28.471 NotebookApp] Kernel restarted: 0b088d07-f9d0-4244-af4c-424b76f9d1f0
[I 18:34:29.138 NotebookApp] Adapting to protocol v5.1 for kernel 0b088d07-f9d0-4244-af4c-424b76f9d1f0
[I 18:34:29.139 NotebookApp] Restoring connection for 0b088d07-f9d0-4244-af4c-424b76f9d1f0:fc5c2073fd144d56ab3a86a125dc6137
[I 18:34:29.139 NotebookApp] Replaying 5 buffered messages
[I 18:35:37.659 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:39:17.749 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:39:18.690 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 18:39:19.713 NotebookApp] Starting buffering for 0b088d07-f9d0-4244-af4c-424b76f9d1f0:fc5c2073fd144d56ab3a86a125dc6137
[C 22:03:26.392 NotebookApp] received signal 15, stopping
[I 22:03:26.410 NotebookApp] Shutting down 1 kernel
[I 22:03:27.354 NotebookApp] Kernel shutdown: 0b088d07-f9d0-4244-af4c-424b76f9d1f0
[I 14:18:49.136 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 14:18:49.136 NotebookApp] Serving notebooks from local directory: /Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024
[I 14:18:49.137 NotebookApp] The Jupyter Notebook is running at:
[I 14:18:49.137 NotebookApp] http://localhost:8888/?token=929f4a20001563a5ab0398e09be5c71dc3aa3cfca53a94a9
[I 14:18:49.137 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:18:49.144 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/wenbin/Library/Jupyter/runtime/nbserver-2859-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=929f4a20001563a5ab0398e09be5c71dc3aa3cfca53a94a9
[I 14:36:43.925 NotebookApp] Saving file at /Preprocess/FindWords/findwords.py
[W 14:37:11.911 NotebookApp] delete /Preprocess/food_words.txt
[I 14:37:14.989 NotebookApp] Kernel started: 716c9697-aa0f-4c75-be0f-8b4112664463
[W 14:37:15.242 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190506141848 (::1) 11.57ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 14:37:15.698 NotebookApp] Adapting to protocol v5.1 for kernel 716c9697-aa0f-4c75-be0f-8b4112664463
[I 14:39:27.289 NotebookApp] Adapting to protocol v5.1 for kernel 716c9697-aa0f-4c75-be0f-8b4112664463
[W 14:39:27.415 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190506141848 (::1) 2.38ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 14:41:27.198 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 14:43:17.220 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[W 14:44:54.816 NotebookApp] delete /Preprocess/pre_process.py
[I 14:45:26.070 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 14:47:15.435 NotebookApp] Starting buffering for 716c9697-aa0f-4c75-be0f-8b4112664463:59f3f9960deb49e49af7f9c9289da77f
[I 14:47:15.962 NotebookApp] Kernel restarted: 716c9697-aa0f-4c75-be0f-8b4112664463
[I 14:47:16.645 NotebookApp] Adapting to protocol v5.1 for kernel 716c9697-aa0f-4c75-be0f-8b4112664463
[I 14:47:16.646 NotebookApp] Restoring connection for 716c9697-aa0f-4c75-be0f-8b4112664463:59f3f9960deb49e49af7f9c9289da77f
[I 14:47:16.646 NotebookApp] Replaying 5 buffered messages
[I 14:47:27.457 NotebookApp] Saving file at /Preprocess/Preprocess.ipynb
[I 14:48:48.616 NotebookApp] Kernel started: 5bff8891-e5e9-4d09-9b64-df554deb25dd
[W 14:48:48.975 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190506141848 (::1) 3.03ms referer=http://localhost:8888/notebooks/CouchdbNote.ipynb
[I 14:48:49.456 NotebookApp] Adapting to protocol v5.1 for kernel 5bff8891-e5e9-4d09-9b64-df554deb25dd
[I 14:48:50.935 NotebookApp] Starting buffering for 5bff8891-e5e9-4d09-9b64-df554deb25dd:1519572b2e49492c80df951671c64dbe
[W 14:51:27.694 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566629 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 14:51:27.694 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 14:51:27.694 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566629 (::1) 1.06ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 14:51:27.700 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 14:51:27.702 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 14:51:27.705 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 14:51:27.705 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 14:51:27.705 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "6665",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 14:51:27.706 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 6.36ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 14:53:27.709 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566630 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 14:53:27.710 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 14:53:27.710 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566630 (::1) 1.94ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 14:53:27.718 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 14:53:27.721 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 14:53:27.721 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 14:53:27.721 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 14:53:27.722 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "7033",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 14:53:27.722 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 4.14ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 14:55:14.660 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566631 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 14:55:14.661 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 14:55:14.661 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566631 (::1) 1.64ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 14:55:14.665 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 14:55:14.668 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 14:55:14.668 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 14:55:14.668 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 14:55:14.669 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "6903",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 14:55:14.669 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 4.34ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 14:55:15.423 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566632 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 14:55:15.423 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 14:55:15.424 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566632 (::1) 1.47ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 14:55:15.430 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 14:55:15.433 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 14:55:15.434 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 14:55:15.434 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 14:55:15.434 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "6903",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 14:55:15.434 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 6.80ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 14:55:27.192 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566633 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 14:55:27.193 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 14:55:27.193 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566633 (::1) 1.45ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 14:55:27.197 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 14:55:27.201 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 14:55:27.202 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 14:55:27.202 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 14:55:27.202 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "6903",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 14:55:27.203 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 5.78ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 14:57:27.188 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566634 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 14:57:27.188 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 14:57:27.188 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566634 (::1) 1.45ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 14:57:27.194 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 14:57:27.197 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 14:57:27.198 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 14:57:27.198 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 14:57:27.198 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "6903",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 14:57:27.198 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 6.09ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 14:59:27.694 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566635 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 14:59:27.695 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 14:59:27.695 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566635 (::1) 1.29ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 14:59:27.700 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 14:59:27.703 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 14:59:27.704 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 14:59:27.704 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 14:59:27.704 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "6903",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 14:59:27.704 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 5.51ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:01:27.192 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566636 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:01:27.192 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:01:27.192 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566636 (::1) 1.31ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:01:27.198 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:01:27.201 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:01:27.202 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:01:27.202 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:01:27.202 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "7068",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:01:27.202 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 4.99ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:03:27.192 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566637 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:03:27.192 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:03:27.193 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566637 (::1) 1.52ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:03:27.198 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:03:27.200 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:03:27.200 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:03:27.201 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:03:27.201 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "7167",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:03:27.201 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 4.48ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:05:27.194 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566638 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:05:27.194 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:05:27.195 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566638 (::1) 1.46ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:05:27.199 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:05:27.204 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:05:27.204 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:05:27.205 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:05:27.205 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "7167",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:05:27.205 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 6.70ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:07:27.194 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566639 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:07:27.195 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:07:27.195 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566639 (::1) 1.46ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:07:27.200 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:07:27.204 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:07:27.205 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:07:27.205 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:07:27.205 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "7167",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:07:27.205 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 6.47ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:09:27.190 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566640 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:09:27.190 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:09:27.191 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566640 (::1) 1.14ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:09:27.195 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:09:27.197 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:09:27.197 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:09:27.197 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:09:27.198 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "7204",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:09:27.198 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 3.71ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:11:04.510 NotebookApp] Kernel started: 9d93ec58-08b5-46ac-b787-a1513426be71
[W 15:11:04.804 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190506141848 (::1) 3.11ms referer=http://localhost:8888/notebooks/ServerNote.ipynb
[I 15:11:05.269 NotebookApp] Adapting to protocol v5.1 for kernel 9d93ec58-08b5-46ac-b787-a1513426be71
[W 15:11:27.698 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566641 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:11:27.698 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:11:27.698 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566641 (::1) 1.32ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:11:27.704 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:11:27.706 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:11:27.706 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:11:27.707 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:11:27.707 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "7231",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:11:27.707 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 4.01ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:13:04.711 NotebookApp] Saving file at /ServerNote.ipynb
[W 15:13:27.197 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566642 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:13:27.197 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:13:27.197 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566642 (::1) 1.46ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:13:27.202 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:13:27.205 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:13:27.205 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:13:27.206 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:13:27.206 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "7272",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:13:27.206 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 4.42ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:15:27.197 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566643 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:15:27.197 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:15:27.197 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566643 (::1) 1.50ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:15:27.202 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:15:27.206 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:15:27.207 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:15:27.207 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:15:27.208 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "7272",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:15:27.208 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 6.24ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:17:27.199 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566644 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:17:27.199 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:17:27.199 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566644 (::1) 1.41ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:17:27.204 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:17:27.208 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:17:27.208 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:17:27.209 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:17:27.209 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "7272",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:17:27.209 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 5.88ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:19:27.200 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566645 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:19:27.200 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:19:27.200 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566645 (::1) 1.42ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:19:27.205 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:19:27.209 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:19:27.210 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:19:27.210 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:19:27.210 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "7272",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:19:27.210 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 6.29ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:21:27.198 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566646 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:21:27.199 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:21:27.199 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566646 (::1) 1.44ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:21:27.210 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:21:27.212 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:21:27.213 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:21:27.213 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:21:27.213 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "7372",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:21:27.213 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 4.55ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:22:24.118 NotebookApp] Kernel interrupted: 716c9697-aa0f-4c75-be0f-8b4112664463
[I 15:22:26.832 NotebookApp] Starting buffering for 716c9697-aa0f-4c75-be0f-8b4112664463:59f3f9960deb49e49af7f9c9289da77f
[E 15:22:27.449 NotebookApp] Failed to run command:
    ['/usr/local/opt/python3/bin/python3.6', '-m', 'ipykernel_launcher', '-f', '/Users/wenbin/Library/Jupyter/runtime/kernel-716c9697-aa0f-4c75-be0f-8b4112664463.json']
        PATH='/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess', 'start_new_session': True}
    
[E 15:22:27.450 NotebookApp] Exception restarting kernel
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 85, in post
        yield gen.maybe_future(km.restart_kernel(kernel_id))
      File "/Users/wenbin/Library/Python/3.6/lib/python/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/Users/wenbin/Library/Python/3.6/lib/python/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/Users/wenbin/Library/Python/3.6/lib/python/site-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 287, in restart_kernel
        yield gen.maybe_future(super(MappingKernelManager, self).restart_kernel(kernel_id))
      File "/Users/wenbin/Library/Python/3.6/lib/python/site-packages/jupyter_client/multikernelmanager.py", line 33, in wrapped
        r = method(*args, **kwargs)
      File "/Users/wenbin/Library/Python/3.6/lib/python/site-packages/jupyter_client/manager.py", line 367, in restart_kernel
        self.start_kernel(**self._launch_args)
      File "/Users/wenbin/Library/Python/3.6/lib/python/site-packages/jupyter_client/manager.py", line 258, in start_kernel
        **kw)
      File "/Users/wenbin/Library/Python/3.6/lib/python/site-packages/jupyter_client/manager.py", line 203, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/Users/wenbin/Library/Python/3.6/lib/python/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess': '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess'
[E 15:22:27.470 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "0",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:22:27.471 NotebookApp] 500 POST /api/kernels/716c9697-aa0f-4c75-be0f-8b4112664463/restart (::1) 636.48ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:22:27.476 NotebookApp] Discarding 2 buffered messages for 716c9697-aa0f-4c75-be0f-8b4112664463:59f3f9960deb49e49af7f9c9289da77f
[I 15:22:27.477 NotebookApp] Kernel shutdown: 716c9697-aa0f-4c75-be0f-8b4112664463
[W 15:22:27.477 NotebookApp] Got events for closed stream None
[W 15:22:27.477 NotebookApp] Got events for closed stream None
[I 15:22:27.491 NotebookApp] Kernel started: f8974310-2ee6-454e-b832-679e2ff2a01d
[I 15:22:28.079 NotebookApp] Adapting to protocol v5.1 for kernel f8974310-2ee6-454e-b832-679e2ff2a01d
[I 15:22:44.937 NotebookApp] Starting buffering for f8974310-2ee6-454e-b832-679e2ff2a01d:59f3f9960deb49e49af7f9c9289da77f
[I 15:22:45.253 NotebookApp] Kernel restarted: f8974310-2ee6-454e-b832-679e2ff2a01d
[I 15:22:45.882 NotebookApp] Adapting to protocol v5.1 for kernel f8974310-2ee6-454e-b832-679e2ff2a01d
[I 15:22:45.883 NotebookApp] Restoring connection for f8974310-2ee6-454e-b832-679e2ff2a01d:59f3f9960deb49e49af7f9c9289da77f
[I 15:22:45.883 NotebookApp] Replaying 6 buffered messages
[W 15:23:27.194 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566647 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:23:27.194 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:23:27.195 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566647 (::1) 1.52ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:23:27.200 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:23:27.203 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:23:27.203 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:23:27.204 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:23:27.204 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "6935",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:23:27.205 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 5.45ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:25:27.194 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566648 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:25:27.195 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:25:27.195 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566648 (::1) 1.17ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:25:27.199 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:25:27.202 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:25:27.202 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:25:27.203 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:25:27.203 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "7060",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:25:27.203 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 4.57ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:27:27.561 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566649 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:27:27.561 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:27:27.561 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566649 (::1) 1.35ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:27:28.002 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:27:28.010 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:27:28.011 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:27:28.011 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:27:28.011 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "209577",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:27:28.011 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 12.08ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:28:35.345 NotebookApp] Starting buffering for 9d93ec58-08b5-46ac-b787-a1513426be71:ceb9321ac7b34f408f30b907be0c98a6
[W 15:29:07.641 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566650 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:29:07.641 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:29:07.641 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566650 (::1) 1.29ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:29:07.648 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:29:07.651 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:29:07.651 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:29:07.651 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:29:07.652 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "9351",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:29:07.652 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 4.48ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:29:15.565 NotebookApp] Kernel started: 295f198c-2028-4599-b1cb-717f92be1542
[W 15:29:15.875 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190506141848 (::1) 3.35ms referer=http://localhost:8888/notebooks/Analyze/Preprocess.ipynb
[I 15:29:16.249 NotebookApp] Adapting to protocol v5.1 for kernel 295f198c-2028-4599-b1cb-717f92be1542
[I 15:29:16.732 NotebookApp] Starting buffering for 295f198c-2028-4599-b1cb-717f92be1542:e8e97143be9e401c84ed57614ee62629
[W 15:29:27.438 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566651 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:29:27.438 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:29:27.438 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566651 (::1) 1.32ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:29:27.461 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:29:27.465 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:29:27.465 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:29:27.466 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:29:27.466 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "9351",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:29:27.466 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 6.50ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:31:00.694 NotebookApp] Kernel shutdown: 5bff8891-e5e9-4d09-9b64-df554deb25dd
[I 15:31:01.831 NotebookApp] Kernel shutdown: 9d93ec58-08b5-46ac-b787-a1513426be71
[I 15:31:10.825 NotebookApp] Kernel shutdown: f8974310-2ee6-454e-b832-679e2ff2a01d
[W 15:31:27.200 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566652 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:31:27.200 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:31:27.201 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566652 (::1) 1.42ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:31:27.206 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:31:27.208 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:31:27.209 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:31:27.209 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:31:27.210 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "9711",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:31:27.210 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 4.94ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:33:27.200 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566653 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:33:27.200 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:33:27.201 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566653 (::1) 1.43ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:33:27.205 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:33:27.208 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:33:27.209 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:33:27.209 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:33:27.210 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "7943",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:33:27.210 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 4.93ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:35:27.199 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566654 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:35:27.199 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:35:27.200 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566654 (::1) 1.42ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:35:27.204 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:35:27.207 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:35:27.207 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:35:27.207 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:35:27.208 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "8040",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:35:27.208 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 4.25ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:37:27.203 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566655 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:37:27.203 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:37:27.204 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566655 (::1) 1.49ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:37:27.208 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:37:27.212 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:37:27.213 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:37:27.213 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:37:27.214 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "8040",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:37:27.214 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 6.19ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:38:42.847 NotebookApp] 404 POST /api/kernels/f8974310-2ee6-454e-b832-679e2ff2a01d/interrupt (::1): Kernel does not exist: f8974310-2ee6-454e-b832-679e2ff2a01d
[W 15:38:42.847 NotebookApp] Kernel does not exist: f8974310-2ee6-454e-b832-679e2ff2a01d
[W 15:38:42.847 NotebookApp] 404 POST /api/kernels/f8974310-2ee6-454e-b832-679e2ff2a01d/interrupt (::1) 1.77ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:39:03.496 NotebookApp] 404 POST /api/kernels/f8974310-2ee6-454e-b832-679e2ff2a01d/interrupt (::1): Kernel does not exist: f8974310-2ee6-454e-b832-679e2ff2a01d
[W 15:39:03.496 NotebookApp] Kernel does not exist: f8974310-2ee6-454e-b832-679e2ff2a01d
[W 15:39:03.496 NotebookApp] 404 POST /api/kernels/f8974310-2ee6-454e-b832-679e2ff2a01d/interrupt (::1) 1.35ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:39:27.204 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566656 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:39:27.204 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:39:27.205 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566656 (::1) 1.46ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:39:27.209 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:39:27.212 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:39:27.213 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:39:27.213 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:39:27.213 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "8046",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:39:27.213 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 4.80ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[E 15:39:35.446 NotebookApp] Exception restarting kernel
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 85, in post
        yield gen.maybe_future(km.restart_kernel(kernel_id))
      File "/Users/wenbin/Library/Python/3.6/lib/python/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/Users/wenbin/Library/Python/3.6/lib/python/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/Users/wenbin/Library/Python/3.6/lib/python/site-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 286, in restart_kernel
        self._check_kernel_id(kernel_id)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 366, in _check_kernel_id
        raise web.HTTPError(404, u'Kernel does not exist: %s' % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: f8974310-2ee6-454e-b832-679e2ff2a01d)
[E 15:39:35.447 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "0",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:39:35.447 NotebookApp] 500 POST /api/kernels/f8974310-2ee6-454e-b832-679e2ff2a01d/restart (::1) 1.34ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[W 15:39:35.457 NotebookApp] 404 DELETE /api/sessions/982c07c7-1ae9-4d93-9521-b3de452c89e0 (::1): Session not found: session_id='982c07c7-1ae9-4d93-9521-b3de452c89e0'
[W 15:39:35.457 NotebookApp] Session not found: session_id='982c07c7-1ae9-4d93-9521-b3de452c89e0'
[W 15:39:35.458 NotebookApp] 404 DELETE /api/sessions/982c07c7-1ae9-4d93-9521-b3de452c89e0 (::1) 1.33ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:39:35.476 NotebookApp] Kernel started: b4083e6d-43c1-43a6-bcd5-e5b889f81856
[I 15:39:36.076 NotebookApp] Adapting to protocol v5.1 for kernel b4083e6d-43c1-43a6-bcd5-e5b889f81856
[W 15:40:04.813 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566657 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:40:04.814 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:40:04.814 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566657 (::1) 1.33ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:40:04.820 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:40:04.823 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:40:04.824 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:40:04.824 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:40:04.824 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "8046",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:40:04.824 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 5.52ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:40:08.281 NotebookApp] Kernel shutdown: 295f198c-2028-4599-b1cb-717f92be1542
[I 15:40:09.113 NotebookApp] Kernel shutdown: b4083e6d-43c1-43a6-bcd5-e5b889f81856
[W 15:40:14.403 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566658 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:40:14.404 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:40:14.404 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566658 (::1) 1.59ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:40:14.411 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:40:14.415 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:40:14.416 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:40:14.416 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:40:14.416 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "8046",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:40:14.416 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 5.79ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:40:18.669 NotebookApp] Kernel started: d284c66f-a5bb-4d42-b4c0-8422539d3297
[W 15:40:18.962 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190506141848 (::1) 2.60ms referer=http://localhost:8888/notebooks/Analyze/Preprocess.ipynb
[I 15:40:19.315 NotebookApp] Adapting to protocol v5.1 for kernel d284c66f-a5bb-4d42-b4c0-8422539d3297
[W 15:41:27.710 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566659 (::1): No such file or directory: Preprocess/Preprocess.ipynb
[W 15:41:27.710 NotebookApp] No such file or directory: Preprocess/Preprocess.ipynb
[W 15:41:27.710 NotebookApp] 404 GET /api/contents/Preprocess/Preprocess.ipynb?content=0&_=1557117566659 (::1) 1.34ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:41:27.716 NotebookApp] Uploading file to /Preprocess/Preprocess.ipynb
[E 15:41:27.720 NotebookApp] Error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 471, in save
        self._save_notebook(os_path, nb)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:41:27.720 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1): Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[W 15:41:27.720 NotebookApp] Unexpected error while saving file: Preprocess/Preprocess.ipynb [Errno 2] No such file or directory: '/Users/wenbin/Desktop/Unimelb courses/COMP90024 CCC/Assignment2/90024/Preprocess/Preprocess.ipynb'
[E 15:41:27.721 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "8046",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7",
      "Cookie": "_xsrf=2|33479048|377b108e8d93b9325473558c3e5711cb|1555048610; username-localhost-8891=\"2|1:0|10:1556696819|23:username-localhost-8891|44:ZjgwNjM3NGY2ZTNjNGQ5ZWIyMzI4MWUzNTg4OWFkMmM=|6b719ed85bfe7e66df2f7d71d60f192eb15660a63473a6b95b9c22a80f44b16c\"; username-localhost-8892=\"2|1:0|10:1556807300|23:username-localhost-8892|44:NjI3ZGNkYjJhYWNkNGFkN2FmMGY4MjA1NGU4N2E4ZTA=|3c4749bfcabb9293863a60aad1279b3795202931aafa9c71100006168cb1aae9\"; username-localhost-8889=\"2|1:0|10:1556957009|23:username-localhost-8889|44:MjkxNmM4ZDNiNTE1NGNjMTlkZjYwZTkxNjFhYWMwMGM=|ae58776c504848ce9aa2b5905f4050d7aa19203a6285f93eec3a137c0a2fc359\"; username-localhost-8890=\"2|1:0|10:1557038023|23:username-localhost-8890|44:ODNlYzYxOGJhY2FmNDY5M2I0OTk1YTM4NmE0NDA2YmY=|7fce4556075d20f4a1622794f6a6624bb5b626a276f328d63b697c1cbb8add99\"; username-localhost-8888=\"2|1:0|10:1557116331|23:username-localhost-8888|44:ZWU1MDZiNGIxNTc2NGFkODkxMjNjMTczN2FkMGNlOGY=|8e7bea040f70841d3db6dec30ff25d3c5bd77d4967a9dd7b18f17f1fc79adf23\""
    }
[E 15:41:27.721 NotebookApp] 500 PUT /api/contents/Preprocess/Preprocess.ipynb (::1) 5.92ms referer=http://localhost:8888/notebooks/Preprocess/Preprocess.ipynb
[I 15:41:40.689 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 15:42:18.665 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 15:46:19.102 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 15:48:18.666 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 15:50:18.678 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 15:52:18.669 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 15:54:18.673 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 15:56:18.669 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 15:58:18.682 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:06:40.628 NotebookApp] Kernel interrupted: d284c66f-a5bb-4d42-b4c0-8422539d3297
[I 16:08:18.672 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:10:18.676 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:12:18.926 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:14:18.680 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:16:19.127 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:18:18.677 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:18:27.543 NotebookApp] Starting buffering for d284c66f-a5bb-4d42-b4c0-8422539d3297:06d2c9839ea74fe19a354a7c2c8ada97
[I 16:18:28.273 NotebookApp] Kernel restarted: d284c66f-a5bb-4d42-b4c0-8422539d3297
[I 16:18:28.898 NotebookApp] Adapting to protocol v5.1 for kernel d284c66f-a5bb-4d42-b4c0-8422539d3297
[I 16:18:28.899 NotebookApp] Restoring connection for d284c66f-a5bb-4d42-b4c0-8422539d3297:06d2c9839ea74fe19a354a7c2c8ada97
[I 16:18:28.900 NotebookApp] Replaying 5 buffered messages
[I 16:20:18.671 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:22:18.672 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:24:18.679 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:26:18.680 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:32:18.733 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:33:16.901 NotebookApp] Saving file at /Analyze/FindWords/food_words.txt
[I 16:33:53.648 NotebookApp] Saving file at /Analyze/FindWords/food_words.txt
[I 16:34:18.686 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:36:18.684 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:38:18.873 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:40:18.956 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:41:34.060 NotebookApp] Starting buffering for d284c66f-a5bb-4d42-b4c0-8422539d3297:06d2c9839ea74fe19a354a7c2c8ada97
[I 16:41:34.791 NotebookApp] Kernel restarted: d284c66f-a5bb-4d42-b4c0-8422539d3297
[I 16:41:35.366 NotebookApp] Adapting to protocol v5.1 for kernel d284c66f-a5bb-4d42-b4c0-8422539d3297
[I 16:41:35.367 NotebookApp] Restoring connection for d284c66f-a5bb-4d42-b4c0-8422539d3297:06d2c9839ea74fe19a354a7c2c8ada97
[I 16:41:35.367 NotebookApp] Replaying 3 buffered messages
[I 16:42:18.755 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:46:18.683 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 16:48:18.699 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 17:41:39.427 NotebookApp] Kernel started: 5dd58f15-5695-4292-8a35-ffbf7a6f694b
[W 17:41:39.798 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190506141848 (::1) 2.83ms referer=http://localhost:8888/notebooks/CouchdbNote.ipynb
[I 17:41:40.120 NotebookApp] Adapting to protocol v5.1 for kernel 5dd58f15-5695-4292-8a35-ffbf7a6f694b
[I 17:41:40.563 NotebookApp] Starting buffering for 5dd58f15-5695-4292-8a35-ffbf7a6f694b:5d61a8f4937844ee9789088cecde4a32
[I 17:41:42.938 NotebookApp] Kernel started: bc2e3f5a-3d44-4a56-8fc6-484c8e7e4a37
[W 17:41:43.225 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190506141848 (::1) 2.51ms referer=http://localhost:8888/notebooks/One%20Click.ipynb
[I 17:41:43.609 NotebookApp] Adapting to protocol v5.1 for kernel bc2e3f5a-3d44-4a56-8fc6-484c8e7e4a37
[I 17:41:52.814 NotebookApp] Saving file at /One Click.ipynb
[I 17:41:52.845 NotebookApp] Starting buffering for bc2e3f5a-3d44-4a56-8fc6-484c8e7e4a37:9dd3f9e4c9c84fdb8e4c51db6eae4239
[I 17:54:36.043 NotebookApp] Starting buffering for d284c66f-a5bb-4d42-b4c0-8422539d3297:06d2c9839ea74fe19a354a7c2c8ada97
[I 17:56:16.887 NotebookApp] Adapting to protocol v5.1 for kernel d284c66f-a5bb-4d42-b4c0-8422539d3297
[W 17:56:16.971 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190506141848 (::1) 2.38ms referer=http://localhost:8888/notebooks/Analyze/Preprocess.ipynb
[I 17:58:13.434 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:04:14.099 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:06:13.421 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:07:10.110 NotebookApp] Copying Background/MyCouchdb/geo_melb/melb.json to /Background/MyCouchdb/geo_melb
[I 18:08:13.420 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[W 18:08:37.425 NotebookApp] delete /Analyze/melb.json
[I 18:10:13.411 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:12:13.414 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:14:13.412 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:16:13.413 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:18:13.415 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:20:13.419 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:21:41.662 NotebookApp] Starting buffering for d284c66f-a5bb-4d42-b4c0-8422539d3297:3591d6340cbb4b3aa7ac3aab8a0e5af3
[I 18:21:42.388 NotebookApp] Kernel restarted: d284c66f-a5bb-4d42-b4c0-8422539d3297
[I 18:21:43.059 NotebookApp] Adapting to protocol v5.1 for kernel d284c66f-a5bb-4d42-b4c0-8422539d3297
[I 18:21:43.060 NotebookApp] Restoring connection for d284c66f-a5bb-4d42-b4c0-8422539d3297:3591d6340cbb4b3aa7ac3aab8a0e5af3
[I 18:21:43.060 NotebookApp] Replaying 3 buffered messages
[I 18:22:13.402 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:22:25.747 NotebookApp] Kernel interrupted: d284c66f-a5bb-4d42-b4c0-8422539d3297
[I 18:24:13.407 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:26:13.408 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:28:13.407 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:30:13.406 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:31:52.681 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:32:13.410 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:34:13.416 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:36:13.414 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:37:02.171 NotebookApp] Starting buffering for d284c66f-a5bb-4d42-b4c0-8422539d3297:3591d6340cbb4b3aa7ac3aab8a0e5af3
[I 18:37:05.479 NotebookApp] Adapting to protocol v5.1 for kernel d284c66f-a5bb-4d42-b4c0-8422539d3297
[W 18:37:05.691 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190506141848 (::1) 2.70ms referer=http://localhost:8888/notebooks/Analyze/Preprocess.ipynb
[I 18:39:05.322 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:49:05.317 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:49:16.239 NotebookApp] Starting buffering for d284c66f-a5bb-4d42-b4c0-8422539d3297:36090bd4ff6f41298bd37d26e108a1c7
[I 18:49:16.859 NotebookApp] Kernel restarted: d284c66f-a5bb-4d42-b4c0-8422539d3297
[I 18:49:17.617 NotebookApp] Adapting to protocol v5.1 for kernel d284c66f-a5bb-4d42-b4c0-8422539d3297
[I 18:49:17.618 NotebookApp] Restoring connection for d284c66f-a5bb-4d42-b4c0-8422539d3297:36090bd4ff6f41298bd37d26e108a1c7
[I 18:49:17.618 NotebookApp] Replaying 3 buffered messages
[I 18:51:05.745 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:55:05.322 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
[I 18:56:32.691 NotebookApp] Saving file at /Analyze/Preprocess.ipynb
